//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Probka
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Состав расчета.
    /// </summary>
    // *** Start programmer edit section *** (СоставРасчета CustomAttributes)

    // *** End programmer edit section *** (СоставРасчета CustomAttributes)
    [AutoAltered()]
    [Caption("Состав расчета")]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("СоставРасчетаE", new string[] {
            "Тип as \'Тип\'",
            "Наименование as \'Наименование\'",
            "Сумма as \'Сумма\'",
            "Ндфл as \'Ндфл\'",
            "Взносы as \'Взносы\'",
            "Всего as \'Всего\'"})]
    public class СоставРасчета : ICSSoft.STORMNET.DataObject
    {
        
        private IIS.Probka.Тип fТип;
        
        private double fНаименование;
        
        private double fСумма;
        
        private double fНдфл;
        
        private double fВзносы;
        
        private double fВсего;
        
        private IIS.Probka.РасчетныйЛист fРасчетныйЛист;
        
        // *** Start programmer edit section *** (СоставРасчета CustomMembers)

        // *** End programmer edit section *** (СоставРасчета CustomMembers)

        
        /// <summary>
        /// Взносы.
        /// </summary>
        // *** Start programmer edit section *** (СоставРасчета.Взносы CustomAttributes)

        // *** End programmer edit section *** (СоставРасчета.Взносы CustomAttributes)
        public virtual double Взносы
        {
            get
            {
                // *** Start programmer edit section *** (СоставРасчета.Взносы Get start)

                // *** End programmer edit section *** (СоставРасчета.Взносы Get start)
                double result = this.fВзносы;
                // *** Start programmer edit section *** (СоставРасчета.Взносы Get end)

                // *** End programmer edit section *** (СоставРасчета.Взносы Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (СоставРасчета.Взносы Set start)

                // *** End programmer edit section *** (СоставРасчета.Взносы Set start)
                this.fВзносы = value;
                // *** Start programmer edit section *** (СоставРасчета.Взносы Set end)

                // *** End programmer edit section *** (СоставРасчета.Взносы Set end)
            }
        }
        
        /// <summary>
        /// Всего.
        /// </summary>
        // *** Start programmer edit section *** (СоставРасчета.Всего CustomAttributes)

        // *** End programmer edit section *** (СоставРасчета.Всего CustomAttributes)
        public virtual double Всего
        {
            get
            {
                // *** Start programmer edit section *** (СоставРасчета.Всего Get start)

                // *** End programmer edit section *** (СоставРасчета.Всего Get start)
                double result = this.fВсего;
                // *** Start programmer edit section *** (СоставРасчета.Всего Get end)

                // *** End programmer edit section *** (СоставРасчета.Всего Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (СоставРасчета.Всего Set start)

                // *** End programmer edit section *** (СоставРасчета.Всего Set start)
                this.fВсего = value;
                // *** Start programmer edit section *** (СоставРасчета.Всего Set end)

                // *** End programmer edit section *** (СоставРасчета.Всего Set end)
            }
        }
        
        /// <summary>
        /// Наименование.
        /// </summary>
        // *** Start programmer edit section *** (СоставРасчета.Наименование CustomAttributes)

        // *** End programmer edit section *** (СоставРасчета.Наименование CustomAttributes)
        public virtual double Наименование
        {
            get
            {
                // *** Start programmer edit section *** (СоставРасчета.Наименование Get start)

                // *** End programmer edit section *** (СоставРасчета.Наименование Get start)
                double result = this.fНаименование;
                // *** Start programmer edit section *** (СоставРасчета.Наименование Get end)

                // *** End programmer edit section *** (СоставРасчета.Наименование Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (СоставРасчета.Наименование Set start)

                // *** End programmer edit section *** (СоставРасчета.Наименование Set start)
                this.fНаименование = value;
                // *** Start programmer edit section *** (СоставРасчета.Наименование Set end)

                // *** End programmer edit section *** (СоставРасчета.Наименование Set end)
            }
        }
        
        /// <summary>
        /// Ндфл.
        /// </summary>
        // *** Start programmer edit section *** (СоставРасчета.Ндфл CustomAttributes)

        // *** End programmer edit section *** (СоставРасчета.Ндфл CustomAttributes)
        public virtual double Ндфл
        {
            get
            {
                // *** Start programmer edit section *** (СоставРасчета.Ндфл Get start)

                // *** End programmer edit section *** (СоставРасчета.Ндфл Get start)
                double result = this.fНдфл;
                // *** Start programmer edit section *** (СоставРасчета.Ндфл Get end)

                // *** End programmer edit section *** (СоставРасчета.Ндфл Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (СоставРасчета.Ндфл Set start)

                // *** End programmer edit section *** (СоставРасчета.Ндфл Set start)
                this.fНдфл = value;
                // *** Start programmer edit section *** (СоставРасчета.Ндфл Set end)

                // *** End programmer edit section *** (СоставРасчета.Ндфл Set end)
            }
        }
        
        /// <summary>
        /// Сумма.
        /// </summary>
        // *** Start programmer edit section *** (СоставРасчета.Сумма CustomAttributes)

        // *** End programmer edit section *** (СоставРасчета.Сумма CustomAttributes)
        public virtual double Сумма
        {
            get
            {
                // *** Start programmer edit section *** (СоставРасчета.Сумма Get start)

                // *** End programmer edit section *** (СоставРасчета.Сумма Get start)
                double result = this.fСумма;
                // *** Start programmer edit section *** (СоставРасчета.Сумма Get end)

                // *** End programmer edit section *** (СоставРасчета.Сумма Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (СоставРасчета.Сумма Set start)

                // *** End programmer edit section *** (СоставРасчета.Сумма Set start)
                this.fСумма = value;
                // *** Start programmer edit section *** (СоставРасчета.Сумма Set end)

                // *** End programmer edit section *** (СоставРасчета.Сумма Set end)
            }
        }
        
        /// <summary>
        /// Тип.
        /// </summary>
        // *** Start programmer edit section *** (СоставРасчета.Тип CustomAttributes)

        // *** End programmer edit section *** (СоставРасчета.Тип CustomAttributes)
        public virtual IIS.Probka.Тип Тип
        {
            get
            {
                // *** Start programmer edit section *** (СоставРасчета.Тип Get start)

                // *** End programmer edit section *** (СоставРасчета.Тип Get start)
                IIS.Probka.Тип result = this.fТип;
                // *** Start programmer edit section *** (СоставРасчета.Тип Get end)

                // *** End programmer edit section *** (СоставРасчета.Тип Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (СоставРасчета.Тип Set start)

                // *** End programmer edit section *** (СоставРасчета.Тип Set start)
                this.fТип = value;
                // *** Start programmer edit section *** (СоставРасчета.Тип Set end)

                // *** End programmer edit section *** (СоставРасчета.Тип Set end)
            }
        }
        
        /// <summary>
        /// мастеровая ссылка на шапку IIS.Probka.РасчетныйЛист.
        /// </summary>
        // *** Start programmer edit section *** (СоставРасчета.РасчетныйЛист CustomAttributes)

        // *** End programmer edit section *** (СоставРасчета.РасчетныйЛист CustomAttributes)
        [Agregator()]
        [NotNull()]
        [PropertyStorage(new string[] {
                "РасчетныйЛист"})]
        public virtual IIS.Probka.РасчетныйЛист РасчетныйЛист
        {
            get
            {
                // *** Start programmer edit section *** (СоставРасчета.РасчетныйЛист Get start)

                // *** End programmer edit section *** (СоставРасчета.РасчетныйЛист Get start)
                IIS.Probka.РасчетныйЛист result = this.fРасчетныйЛист;
                // *** Start programmer edit section *** (СоставРасчета.РасчетныйЛист Get end)

                // *** End programmer edit section *** (СоставРасчета.РасчетныйЛист Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (СоставРасчета.РасчетныйЛист Set start)

                // *** End programmer edit section *** (СоставРасчета.РасчетныйЛист Set start)
                this.fРасчетныйЛист = value;
                // *** Start programmer edit section *** (СоставРасчета.РасчетныйЛист Set end)

                // *** End programmer edit section *** (СоставРасчета.РасчетныйЛист Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "СоставРасчетаE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View СоставРасчетаE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("СоставРасчетаE", typeof(IIS.Probka.СоставРасчета));
                }
            }
        }
    }
    
    /// <summary>
    /// Detail array of СоставРасчета.
    /// </summary>
    // *** Start programmer edit section *** (DetailArrayDetailArrayOfСоставРасчета CustomAttributes)

    // *** End programmer edit section *** (DetailArrayDetailArrayOfСоставРасчета CustomAttributes)
    public class DetailArrayOfСоставРасчета : ICSSoft.STORMNET.DetailArray
    {
        
        // *** Start programmer edit section *** (IIS.Probka.DetailArrayOfСоставРасчета members)

        // *** End programmer edit section *** (IIS.Probka.DetailArrayOfСоставРасчета members)

        
        /// <summary>
        /// Construct detail array.
        /// </summary>
        /// <summary>
        /// Returns object with type СоставРасчета by index.
        /// </summary>
        /// <summary>
        /// Adds object with type СоставРасчета.
        /// </summary>
        public DetailArrayOfСоставРасчета(IIS.Probka.РасчетныйЛист fРасчетныйЛист) : 
                base(typeof(СоставРасчета), ((ICSSoft.STORMNET.DataObject)(fРасчетныйЛист)))
        {
        }
        
        public IIS.Probka.СоставРасчета this[int index]
        {
            get
            {
                return ((IIS.Probka.СоставРасчета)(this.ItemByIndex(index)));
            }
        }
        
        public virtual void Add(IIS.Probka.СоставРасчета dataobject)
        {
            this.AddObject(((ICSSoft.STORMNET.DataObject)(dataobject)));
        }
    }
}
